FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /EasyChef/webapp

# Copy the dependencies file to the working directory
COPY requirements.txt .

# Install any needed dependencies specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the content of the local src directory to the working directory
COPY . /EasyChef/webapp

# Command to run the application
CMD ["python", "app.py"]